version: '2'

services:
  data:
    container_name: data
    image: busybox:latest
    volumes:
      - pgdata:/data
      # - pgdata:/data
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRESQL_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      PGDATA: /data/pgdata
    volumes_from:
      - data
  auth:
    container_name: auth
    build: ./auth
    ports:
      - "8081:8081"
    volumes:
      # - ./auth/migrations:/code/migrations
      - ./auth:/code
      - ./test_results:/test_results
    # command: python run.py
    command: python manage.py db migrate
    depends_on:
      - db
  # web:
  #   container_name: web
  #   build: ./web
  #   command: python run.py
  #   volumes:
  #     - ./web/:/code/
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - auth

volumes:
  pgdata:
    external: true
  testing:
    external: true