version: '2'

services:
  data:
    container_name: data
    image: busybox:latest
    volumes:
      - pgdata:/data
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRESQL_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      PGDATA: /data/pgdata
    volumes_from:
      - data
  web:
    container_name: authenticator
    build: ./web
    command: python app.py
    volumes:
      - ./web/:/code/
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
    external: true